version: '3.8'

services:

    db:
        image: mysql
        container_name: group_project
        restart: 
            on-failure
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: cafe
            MYSQL_USER: group4
            MYSQL_PASSWORD: pass
        ports:
            - "33060:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    adminer:
        image: adminer
        container_name: adminer_container
        ports:
            - 8080:8080
